on:
  push:
    branches:
      - "feature/*"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '\ABC-[0-9]* - .+$'
          error: 'Your first line has to contain a feature number'
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature-pr,asap"
          pr_assignee: "jarro06"