name: Schedule post

on:
  pull_request:

jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/sample
      with:
        what_to_log: true
    - uses: ./.github/actions/sample
      with:
        what_to_log: false