name: Schedule post

on:
  pull_request:
  
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/hello-world-action
      with:
        time_range_minutes: 720
        content_directory: content
      id: publish
    - name: Run something else
      if: steps.publish.outputs.is_scheduled == 'true'
      run: echo "It is scheduled!"
